### PR TITLE
feature: create a file

### PR DESCRIPTION
**Pull request by nikyoto**

### CODE REVIEW

**Review by Git-Hannah — APPROVED** [review]
LGTM! :oD

**Review by doemser — APPROVED** [review]
hau raus

**Comment by nikyoto** [comment]
Danke! :)

**Comment by doemser** [comment]
cüs! you just merged, without approval, didnt you? 🙈

**Comment by nikyoto** [comment]
Oops! Didnt mean to do that. Just deleted the hello.json

**Pull request merged**
